[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
astrolabe_smart_account = "aStRoeLaWJCg8wy8wcUGHYBJJaoSUVQrgoUZZdQcWRh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/index.ts"
